import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';
import nodemailer from 'nodemailer';
require('dotenv').config();
import jwt from 'jsonwebtoken';

var salt = bcrypt.genSaltSync(10);

const hashPassword = (password) => {
    return bcrypt.hashSync(password, salt);
};

const comparePassword = (pass, passHash) => {
    return bcrypt.compareSync(pass, passHash);
};

const randomString = () => {
    return uuidv4();
};

const sendEmail = async (toEmail, title, contentHTML) => {
    let transporter = nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 587,
        secure: false,
        auth: {
            user: process.env.EMAIL,
            pass: process.env.PASS_EMAIL,
        },
        tls: {
            rejectUnauthorized: false,
            // minVersion: "TLSv1.2"
        },
    });

    let info = await transporter.sendMail({
        from: `"TBT Hotel" <${process.env.EMAIL}>`,
        to: toEmail,
        subject: title,
        html: contentHTML,
    });
};

const decodeToken = (token, primaryKey) => {
    try {
        var decoded = jwt.verify(token, primaryKey);
        return decoded;
    } catch (e) {
        return null;
    }
};

function removeVietnameseDiacritics(str) {
    const diacriticsMap = {
        à: 'a',
        á: 'a',
        ả: 'a',
        ã: 'a',
        ạ: 'a',
        ă: 'a',
        ắ: 'a',
        ằ: 'a',
        ẳ: 'a',
        ẵ: 'a',
        ặ: 'a',
        â: 'a',
        ấ: 'a',
        ầ: 'a',
        ẩ: 'a',
        ẫ: 'a',
        ậ: 'a',
        đ: 'd',
        è: 'e',
        é: 'e',
        ẻ: 'e',
        ẽ: 'e',
        ẹ: 'e',
        ê: 'e',
        ế: 'e',
        ề: 'e',
        ể: 'e',
        ễ: 'e',
        ệ: 'e',
        ì: 'i',
        í: 'i',
        ỉ: 'i',
        ĩ: 'i',
        ị: 'i',
        ò: 'o',
        ó: 'o',
        ỏ: 'o',
        õ: 'o',
        ọ: 'o',
        ô: 'o',
        ố: 'o',
        ồ: 'o',
        ổ: 'o',
        ỗ: 'o',
        ộ: 'o',
        ơ: 'o',
        ớ: 'o',
        ờ: 'o',
        ở: 'o',
        ỡ: 'o',
        ợ: 'o',
        ù: 'u',
        ú: 'u',
        ủ: 'u',
        ũ: 'u',
        ụ: 'u',
        ư: 'u',
        ứ: 'u',
        ừ: 'u',
        ử: 'u',
        ữ: 'u',
        ự: 'u',
        ỳ: 'y',
        ý: 'y',
        ỷ: 'y',
        ỹ: 'y',
        ỵ: 'y',
    };

    return str.replace(
        /[àáảãạăắằẳẵặâấầẩẫậđèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵ]/g,
        (match) => diacriticsMap[match]
    );
}

const routes = {
    //app
    getProductPromotionHome: '/api/v1/get-product-promotion-home',
    getTopSellProduct: '/api/vi/get-top-sell-product',
    getNewCollectionProduct: '/api/vi/get-new-collection-product',
    getProductFlycam: '/api/v1/get-product-type-flycam',
    getListProductMayLike: '/api/v1/get-list-product-may-like',
    getEvaluateByIdProduct: '/api/v1/get-evaluate-by-id-product',
    searchProduct: '/api/v1/search-product',
    getListBlog: '/api/v1/get-list-blog',
    getListHashTag: '/api/v1/get-list-hashtag',
    getBlogShareProduct: '/api/v1/get-blog-share-product',
    getBlogShareDefault: '/api/v1/get-blog-share-default',
    getBlogById: '/api/v1/get-blog-by-id',
    getCommentBlogByIdBlog: '/api/v1/get-comment-blog-by-id-blog',
    increaseViewBlogById: '/api/v1/increase-view-blog-by-id',
    getListShortVideo: '/api/v1/get-list-short-video',
    getListCommentShortVideoById: '/api/v1/get-list-comment-short-video-by-id',
    getListProductHashTagByIdVideo:
        '/api/v1/get-list-product-hashtag-by-id-video',
    getProductById: '/api/v1/get-product-by-id',
    getListBlogHome: '/api/v1/get-list-blog-home',
    getEventPromotionById: '/api/v1/get-event-promotion-by-id',

    getListEventPromotionHome: '/api/v1/get-list-event-promotion-home',
    getContentEventPromotionById: '/api/v1/get-content-event-promotin-by-id',

    getSuggestProductMobile: '/api/v2/get-suggest-product-mobile',
    getListBlogForyouMobile: '/api/v2/gwt-list-blog-for-you-mobile',
    getListKeywordSearchMobile: '/api/v2/get-list-keyword-search-mobile',

    //admin
    getAllTypeProduct: '/api/get-all-type-product',
    getAllTrademark: '/api/get-all-trademark',
    getListProductByPage: '/api/get-list-product-by-page',
    getProductBySwapAndPage: '/api/get-list-product-by-swap-and-page',
    addTrademark: '/api/add-trademark',
    addTypeProduct: '/api/add-type-product',
    cloudinaryUpload: '/cloudinary-upload',
    createNewProduct: '/api/create-new-product',
    addPromotionByIdProduct: '/api/add-promotion-by-idproduct',
    swapImageProduct: '/api/swap-image-product',
    createNewKeyWord: '/api/v1/create-new-keyword',
    confirmBillById: '/api/v1/confirm-bill-by-id',
    cancelBillById: '/api/v1/cancel-bill-by-id',
    updateTypeProductById: '/api/update-type-produt-by-id',
    updateTrademarkById: '/api/update-trademark-by-id',
    editProductById: '/api/edit-product-by-id',
    blockProduct: '/api/block-product',
    editImageProduct: '/api/edit-image-product',
    deleteTypeProduct: '/api/delete-type-product-by-id',
    deleteTrademarkById: '/api/delete-trademark-by-id',
    deleteErrorProduct: '/api/v1/delete-error-product',
    createNotify_noimage: '/api/v1/create-notify-noimage',
    createNotify_image: '/api/v1/create-notify-image',
    CheckLoginAdminAccessToken: '/api/v1/check-login-admin-access-token',
    createNewUserAdmin: '/api/v1/create-new-user-admin',
    getListUserAdmin: '/api/v1/get-list-user',
    lockUserAdmin: '/api/v1/lock-user',
    createEventPromotion: '/api/v1/create-event-promotion',
    getListEventPromotion: '/api/v1/get-list-event-promotion',
    editEventPromotion: '/api/v1/edit-event-promotion',
    getListBillByTypeAdmin: '/api/v1/get-list-bill-by-type-admin',
    updateStatusBillAdminWeb: '/api/v1/update-status-bill-admin-web',
    getListVideoAdminByPage: '/api/v1/get-list-video-admin-by-page',
    deleteShortVideoAdmin: '/api/v1/delete-short-video-admin',
    getListReportAdmin: '/api/v1/get-list-report-admin',
    skipReportVideoAdmin: '/api/v1/skip-report-video-admin',
    getListBlogAdminByPage: '/api/v1/get-list-blog-admin-by-page',
    deleteBlogAdminById: '/api/v1/delete-blog-admin-by-id',
    getListReportBlogAdmin: '/api/v1/get-list-report-blog-admin',
    skipReportBlogAdmin: '/api/v1/skip-report-blog-admin',
    upLoadImageCoverPromotion: '/api/v1/upload-image-cover-promotion',
    getStatisticalAdmin: '/api/v1/get-statistical-admin',
    StatisticalEvaluateAdmin: '/api/v1/statistical-evaluate-admin',
    getStatisticalSale: '/api/v1/get-statistical-sale',
    getListKeyWordAdmin: '/api/v1/get-list-key-word',
    editKeyWordSearchAdmin: '/api/v1/edit-keyword-search-admin',
    deleteKeyWordAdmin: '/api/v1/delete-keyword-admin',
    getListUserTypeAdmin: '/api/v1/get-list-user-type-admin',
    deleteEventPromotionAdmin: '/api/v1/delete-event-promotion-admin',
    getCountBillOfMonth: '/api/v1/get-count-bill-of-month',
    getMoneyOfMonth: '/api/v1/get-money-of-month',
    getDetailBillByIdAdmin: '/api/v1/get-detail-bill-by-id-admin',
    getInventoryByTypeProduct: '/api/v1/get-inventory-by-type-product',
    adminLogin: '/api/v2/admin-login',
    checkLoginWithAdmin: '/api/v2/check-login-with-admin',

    //music app
    themCaSi: '/api/v2/them-ca-si',
    layDsCaSi: '/api/v2/lay-ds-ca-si',
    xoaCaSi: '/api/v2/xoa-ca-si',
    suaCaSi: '/api/v2/sua-ca-si',
    themBaiHat: '/api/v2/them-bai-hat',
    layDsBaiHat: '/api/v2/lay-ds-bai-hat',
    xoaBaiHat: '/api/v2/xoa-bai-hat',
    suaBaiHat: '/api/v2/sua-bai-hat',
    getListBaiHat: '/api/v2/lay-ds-bai-hat-public',
    themDanhSachPhat: '/api/v2/them-danh-sach-phat',
    layDanhSachPhat: '/api/v2/lay-danh-sach-phat',
    themBaiHatVaoDanhSach: '/api/v2/them-bai-hat-vao-danh-sach',
    layBaiHatTrongDanhSach: '/api/v2/lay-bai-hat-trong-danh-sach',
    xoaBaiHatKhoiDanhSach: '/api/v2/xoa-bai-hat-khoi-danh-sach',
    xoaDanhSachPhat: '/api/v2/xoa-danh-sach-phat',
    layBaiHatCuaCaSi: '/api/v2/lay-bai-hat-cua-ca-si',
    goiYCaSi: '/api/v2/goi-y-ca-si',
    layCaSiById: '/api/v2/lay-ca-si-by-id',
    timKiemBaiHat: '/api/v2/tim-kiem-bai-hat',
    timKiemCaSi: '/api/v2/tim-kiem-ca-si',
    doiTenDanhSach: '/api/v2/doi-ten-danh-sach',
    doiViTriBaiHatTrongDS: '/api/v2/doi-vi-tri-trong-ds',
    layDanhSachThongBao: '/api/v2/lay-danh-sach-thong-bao',
    toggleYeuThichBaiHat: '/api/v2/toggle-yeu-thich-bai-hat',
    kiemTraYeuThichBaiHat: '/api/v2/kiem-tra-yeu-thich-bai-hat',
    layDanhSachBaiHatYeuThich: '/api/v2/lay-danh-sach-bai-hat-yeu-thich',
    toggleQuanTamCaSi: '/api/v2/toggle-quan-tam-ca-si',
    layDanhSachCaSiQuanTam: '/api/v2/lay-ds-ca-si-quan-tam',
    kiemTraQuanTamCaSi: '/api/v2/kiem-tra-quan-tam-ca-si',
    getListRandomBaiHat: '/api/v2/get-list-random-bai-hat',
    addCommentParent: '/api/v2/add-comment-parent',
    addCommentChild: '/api/v2/add-comment-child',
    toggleLikeComment: '/api/v2/toggle-like-comment',
    getListCommentByIdBaiHat: '/api/v2/get-list-comment-by-id-bai-hat',
    getListIdLikeComment: '/api/v2/get-list-id-like-comment',
    tangViewBaiHat: '/api/v2/tang-view-bai-hat',
    timKiemBaiHatById: '/api/v2/tim-kiem-bai-hat-by-id',
    themLoiBaiHat: '/api/v2/them-loi-bai-hat',
    getListLoiBaiHat: '/api/v2/get-list-loi-bai-hat',
    suaLoiBaiHatById: "/api/v2/sua-loi-bai-hat-by-id",
    suaThoiGianBaiHatById: "/api/v2/sua-thoi-gian-bai-hat-by-id",
    xoaLoiBaiHatById: '/api/v2/xoa-loi-bai-hat-by-id',
    getGoiYMVBaiHat: '/api/v2/get-goi-y-mv-bai-hat',
    timKiemMV: '/api/v2/tim-kiem-mv',


    //end music app

    //winform
    getListBillNoConfirm: '/api/v1/get-list-bill-no-confirm',
    getDetailBillAdmin: '/api/v1/get-detail-bill-admin',
    getListImageProductAdmin: '/api/v1/get-list-image-admin',
    getInfoProductAdmin: '/api/v1/get-info-product-admin',
    getClassifyProductAdmin: '/api/v1/get-classify-product-admin',
    getAddressBillAdmin: '/api/v1/get-address-bill-admin',
    confirmBillAdmin: '/api/v1/confirm-bill-admin',
    updateStatusBillAdmin: '/api/v1/update-status-bill-admin',
    getListStatusBillAdmin: '/api/v1/get-list-status-bill-admin',
    //end winform

    //user
    getUserLogin: '/api/get-user-login',
    getAddressUser: '/api/v1/get-address-user',
    getListCartUser: '/api/v1/get-list-cart-user',
    getUserLoginRefreshToken: '/api/v1/get-user-login-refresh-token',
    getListBillByType: '/api/v1/get-list-bill-by-type',
    getBlogEditById: '/api/v1/get-blog-edit-by-id',
    getListBlogUserByPage: '/api/v1/get-list-blog-user-by-page',
    getShortVideoById: '/api/v1/get-short-video-by-id',
    buyProductByCardSucess: '/api/v1/buy-product-by-card/success',
    CreateUser: '/api/create-user',
    verifyCreateUser: '/api/verify-create-user',
    userLogin: '/api/user-login',
    refreshToken: '/api/refresh-token',
    loginGoogle: '/api/login-google',
    loginFacebook: '/api/login-facebook',
    loginGithub: '/api/login-github',
    addProductToCart: '/api/v1/add-product-to-cart',
    addCartOrMoveCart: '/api/v1/add-cart-or-move-cart',
    addNewAddressUser: '/api/v1/add-new-address-user',
    createNewBill: '/api/v1/create-new-bill',
    userRepurchaseBill: '/api/v1/user-repurchase-bill',
    checkKeyVerify: '/api/v1/check-key-verify',
    buyProductByCard: '/api/v1/buy-product-by-card',
    createNewEvaluateProduct: '/api/v1/create-new-evaluate-product',
    uploadImagesEvaluateProduct: '/apit/v1/upload-images-evaluate-product',
    updateVideoEvaluate: '/api/v1/update-video-evaluate',
    createNewBlog: '/api/v1/create-new-blog',
    createNewImageBlog: '/api/v1/create-new-image-blog',
    uploadVideoNewBlog: '/api/v1/upload-new-video-blog',
    uploadVideoEvaluateProduct: '/apit/v1/upload-video-evaluate-product',
    shareProduct: '/api/v1/share-product',
    shareBlog: '/api/v1/share-blog',
    toggleLikeBlog: '/api/v1/toggle-like-blog',
    createNewCommentBlog: '/api/v1/create-new-comment-blog',
    createNewShortVideo: '/api/v1/create-new-short-video',
    uploadCoverImageShortVideo: '/api/v1/upload-cover-image-short-video',
    uploadVideoForShortVideo: '/api/v1/upload-video-for-short-video',
    setDefaultAddress: '/api/v1/set-default-address',
    editAddressUser: '/api/v1/edit-address-user',
    editAmountCartUser: '/api/v1/edit-amount-cart-user',
    chooseProductInCart: '/api/v1/choose-product-in-cart',
    updateClassifyProductInCart: '/api/v1/update-classify-product-in-cart',
    chooseAllProductInCart: '/api/v1/choose-all-product-in-cart',
    userCancelBill: '/api/v1/user-cancel-bill',
    getCodeVeridyForgetPass: '/apt/v1/get-code-verify-forget-pass',
    changePassForget: '/api/v1/change-pass-forget',
    hasReceivedProduct: '/api/v1/has-received-product',
    updataEvaluateProduct: '/api/v1/update-evaluate-product',
    updateProfileUser: '/api/v1/update-profile-user',
    updateAvatarUser: '/api/v1/update-avatar-user',
    getConfirmCodeChangePass: '/api/v1/get-confirm-code-change-pass',
    confirmCodeChangePass: '/api/v1/confirm-code-change-pass',
    updateBlog: '/api/v1/update-blog',
    updateShortVideoById: '/api/v1/update-short-video-by-id',
    editContentBlogUserById: '/api/v1/edit-content-blog-user-by-id',
    updateCommentBlogById: '/api/v1/updete-comment-blog-by-id',
    deleteAddressUser: '/api/v1/delete-address-user',
    deleteVideoEvaluate: '/api/v2/delete-video-evaluate',
    deleteProductInCart: '/api/v1/delete-product-in-cart',
    createNewEvaluateProductFailed:
        '/api/v2/create-new-evaluate-product-failed',
    deleteBlogUserById: '/api/v1/delete-blog-user-by-id',
    deleteCommentBlogById: '/api/v1/delete-comment-blog-by-id',
    getListBlogByIdUser: '/api/v1/get-list-blog-by-id-user',
    saveBlogCollection: '/api/v1/save-blog-collection',
    getListCollectionBlogUserByPage:
        '/api/v1/get-list-collection-blog-user-by-page',
    deleteCollectBlogById: '/api/v1/delete-collect-blog-by-id',
    createCommentShortVideo: '/api/v1/create-comment-short-video',
    deleteCommentShortVideoById: '/api/v1/delete-comment-shortvideo-by-id',
    editCommentShortVideoById: '/api/v1/edit-comment-shortvideo-by-id',
    toggleLikeShortVideo: '/api/v1/toggle-like-shortvideo',
    checkUserLikeShortVideo: '/api/v1/check-user-like-shortvideo',
    saveCollectionShortVideo: '/api/v1/save-collection-short-video',
    CheckSaveCollectionShortVideo: '/api/v1/check-save-collection-short-video',
    getListVideoByIdUser: '/api/v1/get-list-video-by-id-user',
    getUserById: '/api/v1/get-user-by-id',
    deleteShortVideoById: '/api/v1/delete-short-video-by-id',
    checkLikeBlogById: '/api/v1/check-like-blog-by-id',
    checkSaveBlogById: '/api/v1/check-save-blog-by-id',
    getListNotifyAll: '/api/v1/get-list-notify-all',
    getListNotifyByType: '/api/v1/get-list-notify-by-type',
    seenNotifyOfUser: '/api/v1/seen-notify-of-user',
    sendEmailFromContact: '/api/v1/send-email-from-contact',
    createNewReportVideo: '/api/v1/create-new-report-video',
    createNewReportBlog: '/api/v1/create-new-report-blog',
    getBillById: '/api/v2/get-detail-bill-by-id',
    getDetailBillById: '/api/v2/get-detail-bill-by-id-2',
    createNewUserMobile: '/api/v2/create-new-user-mobile',
    verifyCodeForCreateUserMobile: '/api/v2/verify-code-for-create-user-mobile',





    //quanlykhach san
    themBaiVietks: '/api/v1/them-bai-viet-ks',
    layDanhSachBaiViet: '/api/v1/lay-danh-sach-bai-viet-ks',
    layNoiDungBaiVietKS: '/api/v1/lay-noi-dung-bai-viet-ks',
    suaBaiVietks: '/api/v1/sua-bai-viet-ks',
    xoaBaiVietks: '/api/v1/xoa-bai-viet-ks',
    themChiNhanhKS: '/api/v1/them-chi-nhanh-ks',
    layDanhSachChiNhanhKS: '/api/v1/lay-danh-sach-chi-nahnh-ks',
    themPhongKS: '/api/v1/them-phong-khach-san',
    themAnhPhongKS: '/api/v1/them-anh-phong-ks',
    layDanhSachPhongKS: '/api/v2/lay-danh-sach-phong-ks',
    datPhongKSAdmin: '/api/v1/dat-phong-ks-admin',
    checkStatusPhongKS: '/api/v2/check-status-phong-ks',
    huyDatPhongKsAdmin: '/api/v1/huy-dat-phong-ks-admin',
    getInfoKhachHangBySdt: '/api/v1/get-info-khach-hang-by-sdt',
    getListDisableDateDatPhongKS: '/api/v1/get-list-disable-dat-phong-ks',
    getListDatPhongKSTheoThang: '/api/v1/get-list-dat-phong-ks-theo-thang',
    nhanPhongKs: '/api/v1/nhan-phong-ks',
    traPhongKsAdmin: '/api/v1/tra-phong-ks-admin',
    toggleKhoaPhongKSAdmin: '/api/v1/toggle-khoa-phong-ks-admin',
    updateKhuyenMaiPhongKSAdmin: '/api/v1/update-khuyen-mai-phong-ks-admin',
    updateThongTinPhongKsAdmin: '/api/v1/update-thong-tin-phong-ks-admin',
    getListDatPhongKSAllTheoThang: '/api/v1/get-list-dat-phong-ks-all-theo-thang',
    timKiemPhongKsUser: '/api/v1/tim-kiem-phong-ks-user',
    datPhongKSLoai1User: '/api/v1/dat-phong-ks-loai1-user',
    datPhongKSLoai2User: '/api/v1/dat-phong-ks-loai2-user',
    datPhongKSLoai3User: '/api/v1/dat-phong-ks-loai3-user',
    datPhongKSLoai2UserSuccess: '/api/v1/dat-phong-ks-loai2-user-success',
    getListDatPhongByIdKhach: '/api/v1/get-list-dat-phong-by-id-khach',
    guiMaHuyPhongAdmin: '/api/v1/gui-ma-huy-phong-admin',
    huyPhongByUser: '/api/v1/huy-phong-by-user',
    getListChuyenKhoanLoai3: '/api/v1/get-list-chuyen-khoan-loai3',
    huyThanhToanLoai3: '/api/v1/huy-thanh-toan-loai3',
    xacNhanThanhToanLoai3: '/api/v1/xac-nhan-thanh-toan-loai3',
    themNhanVienKS: '/api/v1/them-nhan-vien-ks',
    getListNhanVienKS: '/api/v1/get-list-nhan-vien-ks',
    getBangLuongNhanVienKS: '/api/v1/get-bang-luong-nhan-vien-ks',
    getListKhachHangKS: '/api/v1/get-list-khach-hang-ks',
};

module.exports = {
    hashPassword,
    randomString,
    sendEmail,
    comparePassword,
    decodeToken,
    routes,
    removeVietnameseDiacritics,
};
